import { printMazePath } from "./printMazePath.js";
import { allIndices } from "./recursion/allIndices.js";
import { factorial } from "./recursion/factorial.js";
import { firstIndex } from "./recursion/firstIndex.js";
import { keypadCombination } from "./recursion/keypadCombination.js";
import { lastIndex } from "./recursion/lastIndex.js";
import { maxOfArray } from "./recursion/maxOfArray.js";
import { mazePath } from "./recursion/mazePath.js";
import { mazePathWithJump } from "./recursion/mazePathWithJump.js";
import { minOfArray } from "./recursion/minOfArray.js";
import { power } from "./recursion/power.js";
import { printArray } from "./recursion/printArray.js";
import { printArrayReverse } from "./recursion/printArrayReverse.js";
import { printDecreasing } from "./recursion/printDecreasing.js";
import { printDecreasingIncreasing } from "./recursion/printDecreasingIncreasing.js";
import { printIncreasing } from "./recursion/printIncreasing.js";
import { printKeypadCombination } from "./recursion/printKeypadCombination.js";
import { printMazePathWithJump } from "./recursion/printMazePathWithJump.js";
import { printStairPath } from "./recursion/printStairPath.js";
import { printSubsequence } from "./recursion/printSubsequence.js";
import { printZigZag } from "./recursion/printZigZag.js";
import { stairPath } from "./recursion/stairPath.js";
import { subsequence } from "./recursion/subsequence.js";
import { toh } from "./recursion/toh.js";

// printIncreasing(5);
// printDecreasing(5);
// printZigZag(3);
// printDecreasingIncreasing(5);
// console.log(factorial(6));
// console.log(power(2, 5));
// toh(5, "A", "B", "C");
// printArray([1, 2, 3, 4, 5], 0);
// printArrayReverse([1, 2, 3, 4, 5], 0);
// console.log(maxOfArray([1, 20, 5, 30, 40], 0));
// console.log(minOfArray([10, 20, 5, 30, 40], 0));
// console.log(firstIndex([1, 2, 3, 4, 2, 5, 6], 0, 4));
// console.log(lastIndex([1, 2, 3, 4, 2, 5, 6], 0, 2));
// console.log(allIndices([1, 2, 3, 4, 2, 5, 2, 6, 2], 0, 2, 0));
// console.log(subsequence("abcde"));
// console.log(keypadCombination("19"));
// console.log(stairPath(7));
// console.log(mazePath(1, 1, 3, 3));
// console.log(mazePathWithJump(1, 1, 3, 3));
// printSubsequence("abcd", "");
// printKeypadCombination("123", "");
// printStairPath(5, "");
// printMazePath(1, 1, 3, 3, "");
// printMazePathWithJump(1, 1, 3, 3, "");
